### ISSUE TITLE
Un Logo?

### ISSUE THREAD

**Issue by alanbato** [alanbato/ducky-calculator#5]
Estaría padre que tuvieramos un logo... pero no se diseñar.

Si alguien quiere hacer un logo en paint o algo estaría padre mostrarlo en el README

**Comment by aliciacisnerosm** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/35d9079e-fdd0-4ac7-8e1b-d183dbf41a06-14aea054-1954-41f6-8785-a0839c4b5369-v1.png?transparent=1&palette=1&width=246)

**Comment by robygonzalez** [comment]
![logo](https://user-images.githubusercontent.com/31547394/54650825-c4821800-4a75-11e9-90f3-4b26aec0c6b2.png)

**Comment by alanbato** [comment]
Gracias por el logo @ernestognw! :duck:
